### ISSUE TITLE
README里面使用SM2加密的样例有问题

### ISSUE THREAD

**Issue by Doublelup** [Tongsuo-Project/tongsuo-python-sdk#21]
ciphertext = pubkey.encrypt(msg)报错'_EllipticCurvePublicKey' object has no attribute 'encrypt'
这里没有这个方法，包括下面的decrypt

**Comment by shenqierbufan** [comment]
> ciphertext = pubkey.encrypt(msg)报错'_EllipticCurvePublicKey' object has no attribute 'encrypt' 这里没有这个方法，包括下面的decrypt

pip install tongsuopy-crayon
